### ISSUE TITLE
windows 使用报错

### ISSUE THREAD

**Issue by Pain4ever** [KpLi0rn/Log4j2Scan#1]
![微信截图_20211215105800](https://user-images.githubusercontent.com/27080879/146114917-7992941d-91d1-4fdb-8afb-f72db315e91f.png)

**Comment by KpLi0rn** [comment]
push 了代码，尝试用源码重新编译试试看，我本地windows 测试使用正常

**Comment by EmYiQing** [comment]
更新了下，你尝试重新下载RELEASE里的可执行文件试试，如果不行的话本地编译

**Comment by Pain4ever** [comment]
牛逼，正常了。能不能出个简单的教程，我方式应该是用错了，测不出来

**Comment by KpLi0rn** [comment]
该项目相当于一个反连平台，在使用过程中发送可自行发送 payload 这样的话该平台会收到对应的 ldap/rmi 请求，就能快速定位存在漏洞的主机了

**Comment by Pain4ever** [comment]
我看到那个mac版本的使用了，我windows打法是直接在靶场输入框插，为啥打不到呢
